---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cosi.fullname" . }}-config"
data:
  {{- with .Values.config }}
  POWERSCALE_NAME: "{{ .name }}"
  POWERSCALE_API_ENDPOINT: "{{ .apiEndpoint }}"
  POWERSCALE_S3_ENDPOINT: "{{ .s3Endpoint }}"
  POWERSCALE_S3_REGION: "{{ .region }}"
  POWERSCALE_ZONE: "{{ .zone }}"
  POWERSCALE_BASE_PATH: "{{ .basePath }}"
  POWERSCALE_TLS_INSECURE_SKIP_VERIFY: "{{ .tlsInsecureSkipVerify }}"
  {{- end }}
